### ISSUE TITLE
Send Files

### ISSUE THREAD

**Issue by timbremer** [anthonyringoet/node-slack-webhook-cli#72]
Hi! Would it be possible to attatch files to the message?

**Comment by anthonyringoet** [comment]
In the Slack incoming webhook api, you can add 'attachments' to messages. Those can just be key/value but those can also be (public accessible) image links. See datadog example in the [slack docs](https://api.slack.com/docs/message-attachments).

I dont think you can actually add/upload a file using the incoming webhook API only in the [full-blown API](https://api.slack.com/methods/files.upload). If you find more on this, be sure to let me know.
